# Generated by Django 3.0.7 on 2021-06-02 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0012_job_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='upload_resume',
            field=models.FileField(default=1, upload_to='documents'),
            preserve_default=False,
        ),
    ]
